name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ui_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Install npm dependencies
      run: npm install
    - name: Download Playwright browsers
      run: npx playwright install
    - name: Start backend
      run: npm run start-be &
    - name: Start frontend
      run: npm run start-fe &
    - name: Run UI tests
      run: npm run test-ui
  deploy_backend_render:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: ui_tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_WEB_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
  deploy_frontend_render:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: deploy_backend_render
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_STATIC_SITE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}