name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Install npm dependencies
      run: npm install
    - name: Start backend
      run: npm run start-be &
    - name: Start frontend
      run: npm run start-fe &
    - name: Run UI tests
      run: npm run test-ui
